### ISSUE TITLE
Update for TBC Classic?

### ISSUE THREAD

**Issue by hepkat** [jukx/BindPad-Classic#3]
Think you could update it for TBC Classic?

```
1x [string "BindPadMacroFrameTextBackground:OnLoad"]:1: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
self = BindPadMacroFrameTextBackground {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = BindPadMacroFrameTextBackground {
 0 = <userdata>
}
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
```

**Comment by hepkat** [comment]
nevermind I fixed it on my own.

**Comment by hgcow** [comment]
> nevermind I fixed it on my own.

Hey @hepkat, can you tell me how to fix this? I'd like to use the addon too.

**Comment by hepkat** [comment]
https://github.com/hepkat/BindPad-Classic-bcc/releases/tag/c0.2

I forked it and updated it.

So go there and download the [BindPad.c0.2-bcc.zip](https://github.com/hepkat/BindPad-Classic-bcc/releases/download/c0.2/BindPad.c0.2-bcc.zip)

Extract it like you would any other addon. It was a very simple fix. Just removed a small snippet of code from the bindpad.xml file. If you use WowUp or Ajour you can copy and paste the top link into their "install from URL" option as well.
